<?php namespace JF;
/**

Copyright 2021 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-7a9863
Date:    2021-10-21 21:47:46
Version: v3.0.3
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-7a9863",
    "email": {
        "to": "Este campo es requerido",
        "cc": "Please enter a value greater than or equal to {0}",
        "bcc": "",
        "subject": "",
        "template": ""
    },
    "admin": {
        "users": "admin:9a6fe",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": ""
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "Failed to compare two fields.",
        "user": "Please enter a value less than or equal to {0}.",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "NUMERO DE CEDULA DE ESPECIALIDAD"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "CONSTANCIA No.",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Campo requerido*"
                    }
                },
                "addon": {
                    "leftIcon": "fa fa-archive",
                    "rightIcon": ""
                }
            },
            "id": "f4",
            "cid": "c25"
        },
        {
            "label": "FECHA",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": ""
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Campo requerido*"
                    }
                }
            },
            "id": "f5",
            "cid": "c32"
        },
        {
            "label": "NOMBRE COMPLETO",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Campo requerido*"
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "DOMICILIO",
            "field_type": "address",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "labelHide": false,
            "gMapApiKey": "",
            "gaCompleteEnabled": true,
            "gaCountryRestrictions": "mx",
            "gaPostalCodeRestrictions": "",
            "gaLanguage": "es-419",
            "showLabel": false,
            "showPlaceholder": true,
            "showDescription": false,
            "subfields": {
                "addressLine1": {
                    "order": 1,
                    "label": "Address Line1",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "street_number route",
                        "gAddressName": "long_name",
                        "placeholder": "CALLE",
                        "description": "Street address, P.O. box, company name, c\/o",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Campo requerido*"
                            }
                        }
                    }
                },
                "addressLine2": {
                    "order": 2,
                    "label": "Address Line2",
                    "field_options": {
                        "enabled": false,
                        "placeholder": "Unit 1234",
                        "description": "Apartment, suite, unit, building, floor, etc.",
                        "validators": {
                            "required": {
                                "enabled": false,
                                "msg": ""
                            }
                        }
                    }
                },
                "city": {
                    "order": 3,
                    "label": "City",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "locality",
                        "gAddressName": "long_name",
                        "placeholder": "MUNICIPIO",
                        "description": "City",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Campo requerido*"
                            }
                        }
                    }
                },
                "state": {
                    "order": 4,
                    "label": "State \/ Province \/ Region",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "administrative_area_level_1",
                        "gAddressName": "long_name",
                        "placeholder": "CIUDAD",
                        "description": "State \/ Province \/ Region",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Campo requerido*"
                            }
                        }
                    }
                },
                "postalCode": {
                    "order": 5,
                    "label": "Postal \/ Zip Code",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "postal_code",
                        "gAddressName": "long_name",
                        "placeholder": "CODIGO POSTAL",
                        "description": "Postal \/ Zip Code",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Campo requerido*"
                            }
                        }
                    }
                },
                "country": {
                    "order": 6,
                    "label": "Country",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "country",
                        "gAddressName": "long_name",
                        "placeholder": "PAIS",
                        "description": "Country",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Campo requerido*"
                            }
                        }
                    }
                }
            },
            "id": "f6",
            "cid": "c44"
        },
        {
            "label": "Phone",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": false,
                "placeholder": "+xxx-xxx-xxx-xxxx",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-earphone"
                },
                "validators": {
                    "pattern": {
                        "enabled": true,
                        "val": "[+]*[0-9]{0,3}[ -.]*[0-9]{3,4}[ -.]*[0-9]{3,4}[ -.]*[0-9]{4}",
                        "msg": "Invalid phone number"
                    },
                    "phonenumber": {
                        "enabled": false
                    },
                    "maxlength": {
                        "enabled": false
                    },
                    "minlength": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Campo requerido*"
                    }
                }
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "N"
            },
            "id": "f7",
            "cid": "c34"
        },
        {
            "label": "E-MAIL",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Campo requerido*"
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope",
                    "leftText": ""
                }
            },
            "id": "f2",
            "cid": "c2"
        },
        {
            "label": "NOMBRE DE INSTITUCION EDUCATIVA DE EGRESO DE LICENCIATURA",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": [],
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Campo requerido*"
                    },
                    "alphanumeric": {
                        "enabled": true,
                        "msg": "Letras y n\u00fameros por favor*"
                    },
                    "minlength": {
                        "enabled": false
                    }
                }
            },
            "id": "f12",
            "cid": "c71"
        },
        {
            "label": "LICENCIATURA",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": [],
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Campo requerido*"
                    }
                }
            },
            "id": "f13",
            "cid": "c76"
        },
        {
            "label": "ESPECIALIDAD",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": [],
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Campo requerido*"
                    }
                }
            },
            "id": "f14",
            "cid": "c81"
        },
        {
            "label": "NUMERO DE CEDULA DE LICENCIATURA",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "min": {
                        "enabled": false
                    },
                    "compareTo": {
                        "enabled": false
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Campo requerido*"
                    }
                }
            },
            "id": "f15",
            "cid": "c86"
        },
        {
            "label": "NUMERO DE CEDULA DE ESPECIALIDAD",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Campo requerido*"
                    }
                }
            },
            "id": "f16",
            "cid": "c91"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "ENVIAR",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "always"
    },
    "licenseKey": "",
    "twilio": {
        "toPhone": "red",
        "accountSid": "jesus.hinojosa5221@alumnos.udg.mx",
        "authToken": "test"
    }
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class